# syntax=docker/dockerfile:experimental
FROM golang:1.13.8 as dev

WORKDIR /src
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# Copy the go source
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on make build

FROM scratch
COPY --from=dev /src/kube-vip /
ENTRYPOINT ["/kube-vip"]
